[package]
name = "regular_expressions"
version = "0.1.0"
authors = ["jessicalally <jessica.lally19@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
